import { Terminal } from '@xterm/headless'
export interface RasterGlowSettings { brightness:number; contrast:number; focus:number; glow:number; flicker:number; curvature:number; persistence:number }
interface Options { cols:number; rows:number; settings?:Partial<RasterGlowSettings>; onData(data:string):void; onResize(size:{cols:number;rows:number}):void }
const defaults:RasterGlowSettings={brightness:1.25,contrast:1.2,focus:.94,glow:1.25,flicker:.6,curvature:.065,persistence:.72}
const colors=['#07140c','#e84b4b','#42e66f','#e5d95b','#4c82e8','#c45cdb','#40d6d6','#c8d6c8','#47604d','#ff6b6b','#68ff92','#fff07a','#72a4ff','#ec86ff','#69ffff','#f2fff2']
function palette(i:number):number[]{if(i<16){const n=parseInt(colors[i].slice(1),16);return[(n>>16)&255,(n>>8)&255,n&255]}if(i<232){const n=i-16,p=(v:number)=>v?55+v*40:0;return[p(Math.floor(n/36)),p(Math.floor(n%36/6)),p(n%6)]}const v=8+(i-232)*10;return[v,v,v]}
function light(c:number[]){const f=(v:number)=>{const s=v/255;return s<=.04045?s/12.92:Math.pow((s+.055)/1.055,2.4)},y=.2126*f(c[0])+.7152*f(c[1])+.0722*f(c[2]);return .045+.955*(y<=216/24389?y*(24389/27)/100:(116*Math.cbrt(y)-16)/100)}
const green=(v:number)=>`rgb(${Math.round(42*v)},${Math.round(255*v)},${Math.round(102*v)})`
export class RasterGlowEngine {
 private term:Terminal;private canvas:HTMLCanvasElement;private glass:HTMLElement;private status:HTMLElement;private live=document.createElement('canvas');private energy=document.createElement('canvas');private settings:RasterGlowSettings;private frame=0;private observer:ResizeObserver;private last=performance.now();private cw=10;private ch=20;private fs=16;private left=40;private top=30;private blink=true
 constructor(private root:HTMLElement,private options:Options){this.settings={...defaults,...options.settings};this.canvas=root.querySelector('.rasterglow__canvas')!;this.glass=root.querySelector('.rasterglow__glass')!;this.status=root.querySelector('.rasterglow__status')!;this.term=new Terminal({cols:options.cols,rows:options.rows,scrollback:5000,allowProposedApi:true});this.term.onData(options.onData);this.term.onBinary(options.onData);root.addEventListener('keydown',this.key);root.addEventListener('paste',this.paste);this.glass.addEventListener('pointerdown',this.pointer);this.glass.addEventListener('pointerup',this.pointerUp);this.glass.addEventListener('pointermove',this.pointerMove);this.glass.addEventListener('wheel',this.wheel,{passive:false});this.observer=new ResizeObserver(this.resize);this.observer.observe(root);document.fonts.ready.then(this.resize);this.frame=requestAnimationFrame(this.animate)}
 write(data:string){this.term.write(data.replace(/\x1b\[([0-9;]*)m/g,(s,p)=>p.split(';').includes('6')?`\x1b[${p.split(';').map((v:string)=>v==='6'?'5':v).join(';')}m`:s))} clear(){this.term.clear()} focus(){this.root.focus()} setSettings(v:Partial<RasterGlowSettings>){Object.assign(this.settings,v)} dispose(){cancelAnimationFrame(this.frame);this.observer.disconnect();this.term.dispose()}
 private resize=()=>{const d=Math.min(2,devicePixelRatio||1),w=this.glass.clientWidth,h=this.glass.clientHeight;this.canvas.width=this.live.width=this.energy.width=Math.max(1,w*d);this.canvas.height=this.live.height=this.energy.height=Math.max(1,h*d);this.left=w*.07;this.top=h*.06;this.fs=Math.max(9,Math.min(21,h*.88/this.options.rows*.76));this.ch=this.fs*1.28;const c=this.live.getContext('2d')!;c.font=`${this.fs}px RasterGlow Mono`;this.cw=c.measureText('M').width;const cols=Math.max(20,Math.floor(w*.86/this.cw)),rows=Math.max(8,Math.floor(h*.88/this.ch));this.term.resize(cols,rows);this.status.textContent=`${cols} × ${rows} CHARACTERS`;this.options.onResize({cols,rows})}
 private key=(e:KeyboardEvent)=>{if(e.ctrlKey&&!e.altKey&&!e.metaKey&&/^[a-z]$/i.test(e.key)){this.options.onData(String.fromCharCode(e.key.toLowerCase().charCodeAt(0)-96));e.preventDefault();return}const k:Record<string,string>={Enter:'\r',Backspace:'\x7f',Tab:'\t',Escape:'\x1b',ArrowUp:'\x1b[A',ArrowDown:'\x1b[B',ArrowRight:'\x1b[C',ArrowLeft:'\x1b[D',Home:'\x1b[H',End:'\x1b[F',Delete:'\x1b[3~',PageUp:'\x1b[5~',PageDown:'\x1b[6~'},v=k[e.key]||(!e.ctrlKey&&!e.metaKey&&e.key.length===1?e.key:'');if(v){this.options.onData(v);e.preventDefault()}}
 private paste=(e:ClipboardEvent)=>{const v=e.clipboardData?.getData('text');if(v){this.options.onData(v);e.preventDefault()}}
 private cell(e:MouseEvent){const r=this.glass.getBoundingClientRect();return{c:Math.max(1,Math.min(this.term.cols,Math.floor((e.clientX-r.left-this.left)/this.cw)+1)),r:Math.max(1,Math.min(this.term.rows,Math.floor((e.clientY-r.top-this.top)/this.ch)+1))}}
 private pointer=(e:PointerEvent)=>{const p=this.cell(e);this.options.onData(`\x1b[<${e.button};${p.c};${p.r}M`);this.glass.setPointerCapture(e.pointerId);e.preventDefault();queueMicrotask(()=>this.root.focus({preventScroll:true}))};private pointerUp=(e:PointerEvent)=>{const p=this.cell(e);this.options.onData(`\x1b[<${e.button};${p.c};${p.r}m`);e.preventDefault()};private lastMove=0;private pointerMove=(e:PointerEvent)=>{if(performance.now()-this.lastMove<45)return;this.lastMove=performance.now();const p=this.cell(e);this.options.onData(`\x1b[<35;${p.c};${p.r}M`)};private wheel=(e:WheelEvent)=>{const p=this.cell(e);this.options.onData(`\x1b[<${e.deltaY<0?64:65};${p.c};${p.r}M`);this.root.focus({preventScroll:true});e.preventDefault()}
 private paint(){const d=this.live.width/Math.max(1,this.glass.clientWidth),c=this.live.getContext('2d')!,b=this.term.buffer.active;c.clearRect(0,0,this.live.width,this.live.height);c.save();c.scale(d,d);c.font=`${this.fs}px RasterGlow Mono`;c.textBaseline='top';c.fontKerning='none';for(let y=0;y<this.term.rows;y++){const line=b.getLine(b.viewportY+y);if(!line)continue;for(let x=0;x<this.term.cols;x++){const cell=line.getCell(x);if(!cell)continue;const read=(fg:boolean)=>{const val=fg?cell.getFgColor():cell.getBgColor(),isRgb=fg?cell.isFgRGB():cell.isBgRGB(),isPal=fg?cell.isFgPalette():cell.isBgPalette();return isRgb?[(val>>16)&255,(val>>8)&255,val&255]:isPal?palette(val):null};let fg=read(true)||[150,220,170],bg=read(false);if(cell.isInverse())[fg,bg]=[bg||[0,0,0],fg];if(bg){c.fillStyle=green(light(bg)*.28);c.fillRect(this.left+x*this.cw,this.top+y*this.ch,this.cw+.4,this.ch+.4)}const s=cell.getChars();if(!s||(cell.isBlink()&&!this.blink))continue;let l=light(fg);if(cell.isBold())l=Math.min(1,l*1.16);c.globalAlpha=cell.isDim()?.42:.78;c.fillStyle=green(l);c.fillText(s,this.left+x*this.cw,this.top+y*this.ch);const span=this.cw*Math.max(1,cell.getWidth());if(cell.isUnderline())c.fillRect(this.left+x*this.cw,this.top+(y+.88)*this.ch,span,1);if(cell.isOverline())c.fillRect(this.left+x*this.cw,this.top+y*this.ch,span,1);x+=Math.max(1,cell.getWidth())-1}}c.restore()}
 private animate=(now:number)=>{const dt=Math.min(.1,(now-this.last)/1000);this.last=now;this.blink=Math.floor(now/500)%2===0;this.paint();const e=this.energy.getContext('2d')!,w=this.canvas.width,h=this.canvas.height;e.globalCompositeOperation='source-over';e.fillStyle=`rgba(0,0,0,${1-Math.pow(this.settings.persistence,dt*8)})`;e.fillRect(0,0,w,h);e.globalCompositeOperation='lighter';e.globalAlpha=.9;e.drawImage(this.live,0,0);const out=this.canvas.getContext('2d')!;out.clearRect(0,0,w,h);out.save();out.filter=`brightness(${this.settings.brightness}) contrast(${this.settings.contrast}) blur(${Math.max(0,(1-this.settings.focus)*1.5)}px) drop-shadow(0 0 ${2+this.settings.glow*3}px rgba(30,255,95,${.12*this.settings.glow}))`;const n=Math.min(240,h),sh=h/n;for(let i=0;i<n;i++){const q=i/(n-1)*.2-.1,j=(Math.random()-.5)*this.settings.flicker*.12,x=q*q*this.settings.curvature*w;out.drawImage(this.energy,0,i*sh,w,sh+1,x+j,i*sh,w-2*x,sh+1)}out.filter='none';out.globalCompositeOperation='multiply';for(let y=2;y<h;y+=4){out.fillStyle='rgba(0,0,0,.2)';out.fillRect(0,y,w,2)}out.restore();this.frame=requestAnimationFrame(this.animate)}
}
