const { Terminal } = require('@xterm/headless');
const { ipcRenderer } = require('electron');
const { win32KeySequence, sgrMouseSequence } = require('./input-protocol');
window.addEventListener('error', event => console.error('UNCAUGHT', event.error?.stack || event.message));

window.retroTerminal = {
  onData: callback => ipcRenderer.on('terminal:data', (_event, data) => callback(data)),
  onExit: callback => ipcRenderer.on('terminal:exit', callback),
  input: data => ipcRenderer.send('terminal:input', data),
  resize: (cols, rows) => ipcRenderer.send('terminal:resize', { cols, rows })
};

const canvas = document.getElementById('phosphor');
const screen = document.getElementById('screenfx');
const gl = canvas.getContext('webgl', { alpha: false, antialias: true });
const current = document.createElement('canvas');
const cctx = current.getContext('2d');

const windowsBuild = Number((process.getSystemVersion?.() || '10.0.19045').split('.').pop()) || 19045;
const term = new Terminal({
  cols: 120, rows: 36, scrollback: 5000, allowProposedApi: true,
  windowOptions: { getWinSizeChars: true },
  windowsPty: { backend: 'conpty', buildNumber: windowsBuild }
});
// Mouse reports generated by xterm's protocol service leave through onData;
// default (non-SGR) reports use the binary channel.
term.onData(data => window.retroTerminal.input(data));
term.onBinary(data => window.retroTerminal.input(data));
const ansi16 = [
  '#07140c', '#e84b4b', '#42e66f', '#e5d95b', '#4c82e8', '#c45cdb', '#40d6d6', '#c8d6c8',
  '#47604d', '#ff6b6b', '#68ff92', '#fff07a', '#72a4ff', '#ec86ff', '#69ffff', '#f2fff2'
];

function paletteColor(index) {
  if (index < 16) return ansi16[index];
  if (index < 232) {
    const n = index - 16;
    const r = Math.floor(n / 36), g = Math.floor((n % 36) / 6), b = n % 6;
    const level = value => value === 0 ? 0 : 55 + value * 40;
    return `rgb(${level(r)},${level(g)},${level(b)})`;
  }
  const gray = 8 + (index - 232) * 10;
  return `rgb(${gray},${gray},${gray})`;
}

function cssRgb(color) {
  if (color[0] === '#') {
    const n = parseInt(color.slice(1), 16);
    return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
  }
  return color.match(/\d+/g).slice(0, 3).map(Number);
}

function sourceFgRgb(cell) {
  if (cell.isFgRGB()) {
    const rgb = cell.getFgColor();
    return [(rgb >> 16) & 255, (rgb >> 8) & 255, rgb & 255];
  }
  if (cell.isFgPalette()) return cssRgb(paletteColor(cell.getFgColor()));
  return [150, 220, 170];
}

function sourceBgRgb(cell) {
  if (cell.isBgRGB()) {
    const rgb = cell.getBgColor();
    return [(rgb >> 16) & 255, (rgb >> 8) & 255, rgb & 255];
  }
  if (cell.isBgPalette()) return cssRgb(paletteColor(cell.getBgColor()));
  return null;
}

function phosphorLevel(rgb, floor = 0.035) {
  if (!rgb) return 0;
  const [r, g, b] = rgb;
  // Convert sRGB to linear light and then to perceptual CIE L*. This keeps
  // equally perceived ANSI colors equally separated on one green phosphor.
  const linear = value => {
    const s = value / 255;
    return s <= 0.04045 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4);
  };
  const luminance = 0.2126 * linear(r) + 0.7152 * linear(g) + 0.0722 * linear(b);
  const lightness = luminance <= 216 / 24389
    ? luminance * (24389 / 27) / 100
    : (116 * Math.cbrt(luminance) - 16) / 100;
  return floor + (1 - floor) * lightness;
}

function green(level) {
  return `rgb(${Math.round(42 * level)},${Math.round(255 * level)},${Math.round(102 * level)})`;
}

function cellPaint(cell) {
  let fg = sourceFgRgb(cell);
  let bg = sourceBgRgb(cell);
  if (cell.isInverse()) [fg, bg] = [bg, fg];
  let fgLevel = fg ? phosphorLevel(fg, 0.035) : 0;
  if (cell.isBold()) fgLevel = Math.min(1, fgLevel * 1.16);
  return {
    fg: fg ? green(fgLevel) : 'rgb(0,0,0)',
    bg: bg ? green(0.018 + phosphorLevel(bg, 0) * 0.255) : null
  };
}
const fontFamily = '"AsciiTeX Unicode Mono", monospace';
let cols = 120;
let rows = 36;
let cellW = 10;
let cellH = 20;
let fontSize = 16;
let textLeft = 68;
let textTop = 48;
let last = performance.now();
let cursorVisible = true;
let blinkVisible = true;
let lastScrollAt = -Infinity;
let lastTerminalDataAt = -Infinity;
let lastBaseY = 0;
let lastAlternateBuffer = false;
let mouseDiagnostic = '';
let forcedMouseCapture = false;
let mouseTestOverlay = false;
let mouseTestMessage = 'Waiting for mouse events ...';
let mouseCalibration = false;
let calibrationMessage = 'Click each target. The measured cell and error will appear here.';

function calibrationTargets() {
  return [
    { name: 'TOP LEFT', col: 4, row: 4 },
    { name: 'TOP RIGHT', col: Math.max(4, cols - 17), row: 4 },
    { name: 'CENTER', col: Math.max(4, Math.floor(cols / 2) - 6), row: Math.max(4, Math.floor(rows / 2) - 1) },
    { name: 'BOTTOM LEFT', col: 4, row: Math.max(4, rows - 7) },
    { name: 'BOTTOM RIGHT', col: Math.max(4, cols - 17), row: Math.max(4, rows - 7) }
  ];
}
term.onScroll(() => { lastScrollAt = performance.now(); });

function updateStatus() {
  const suffix = mouseDiagnostic ? ` · ${mouseDiagnostic}` : '';
  document.getElementById('status').textContent = `${cols} × ${rows} ZEICHEN · CTRL+SHIFT+F2 CRT SETUP${suffix}`;
}

function compileShader(type, source) {
  const shader = gl.createShader(type);
  gl.shaderSource(shader, source); gl.compileShader(shader);
  if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) throw new Error(gl.getShaderInfoLog(shader));
  return shader;
}

const glProgram = gl.createProgram();
gl.attachShader(glProgram, compileShader(gl.VERTEX_SHADER, `
  attribute vec2 p; varying vec2 uv;
  void main(){ uv=p*.5+.5; gl_Position=vec4(p,0.,1.); }
`));
gl.attachShader(glProgram, compileShader(gl.FRAGMENT_SHADER, `
  precision mediump float; varying vec2 uv; uniform sampler2D phosphor; uniform sampler2D liveText;
  uniform float barrel; uniform float brightness; uniform float contrast; uniform float focus; uniform float glow;
  uniform float flicker; uniform float time; uniform vec2 resolution;
  float noise2(vec2 p){ return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453); }
  void main(){
    vec2 q=uv*2.0-1.0;
    vec2 source=q*(1.0+barrel*dot(q,q));
    vec2 suv=source*.5+.5;
    // Each small group of raster lines is redrawn with a tiny independent
    // horizontal timing error. Rare wider bands emulate a brief sync wobble.
    float frame=floor(time*32.0);
    float rasterRow=floor(suv.y*resolution.y/2.0);
    float rowNoise=noise2(vec2(rasterRow,frame));
    float band=floor(suv.y*28.0);
    float bandNoise=noise2(vec2(band,floor(time*11.0)));
    float rareBand=step(0.965,bandNoise)*(bandNoise-0.965)/0.035;
    suv.x+=(rowNoise-0.5)*flicker*0.75/resolution.x;
    suv.x+=(noise2(vec2(band,frame))-0.5)*rareBand*flicker*4.0/resolution.x;
    if(suv.x<0.0||suv.x>1.0||suv.y<0.0||suv.y>1.0){ gl_FragColor=vec4(.001,.006,.003,1.); return; }
    vec3 history=texture2D(phosphor,suv).rgb;
    vec3 live=texture2D(liveText,suv).rgb;
    float liveMask=max(live.r,max(live.g,live.b));
    vec3 c=max(live*0.98,history*(1.0-liveMask*focus));
    vec2 px=1.0/resolution;
    vec3 halo=texture2D(phosphor,suv+vec2( 2.0, 0.0)*px).rgb;
    halo+=texture2D(phosphor,suv+vec2(-2.0, 0.0)*px).rgb;
    halo+=texture2D(phosphor,suv+vec2( 0.0, 2.0)*px).rgb;
    halo+=texture2D(phosphor,suv+vec2( 0.0,-2.0)*px).rgb;
    halo+=texture2D(phosphor,suv+vec2( 4.0, 3.0)*px).rgb;
    halo+=texture2D(phosphor,suv+vec2(-4.0,-3.0)*px).rgb;
    halo+=texture2D(phosphor,suv+vec2( 4.0,-3.0)*px).rgb;
    halo+=texture2D(phosphor,suv+vec2(-4.0, 3.0)*px).rgb;
    c+=halo*(0.055*glow);
    float lineGrain=(noise2(vec2(rasterRow,frame+19.0))-0.5)*0.045*flicker;
    float mains=1.0+sin(time*6.2831853*50.0)*0.006*flicker;
    c=max(c+lineGrain,0.0)*mains;
    // Contrast changes the spacing of phosphor intensities (gamma around
    // black); brightness remains an independent beam-current multiplier.
    float beam=max(c.r,max(c.g,c.b));
    float contrasted=pow(clamp(beam,0.0,1.0),contrast)*brightness;
    c*=contrasted/max(beam,0.0001);
    float scanPhase=suv.y*resolution.y*1.5707963;
    float scanline=0.90+0.10*sin(scanPhase);
    float fineBeam=0.98+0.02*sin(scanPhase*2.0);
    c*=scanline*fineBeam;
    float vignette=clamp(1.16-dot(q,q)*.24,0.0,1.0);
    gl_FragColor=vec4(c*vignette,1.0);
  }
`));
gl.linkProgram(glProgram); gl.useProgram(glProgram);
const glBuffer = gl.createBuffer();
gl.bindBuffer(gl.ARRAY_BUFFER, glBuffer);
gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-1,-1, 3,-1, -1,3]), gl.STATIC_DRAW);
const glPosition = gl.getAttribLocation(glProgram, 'p');
gl.enableVertexAttribArray(glPosition); gl.vertexAttribPointer(glPosition, 2, gl.FLOAT, false, 0, 0);
const glTexture = gl.createTexture();
gl.bindTexture(gl.TEXTURE_2D, glTexture);
gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR);
gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true);

// Two GPU textures retain per-pixel phosphor energy. One is read while the
// other is written, then they swap roles (ping-pong feedback).
const feedbackProgram = gl.createProgram();
gl.attachShader(feedbackProgram, compileShader(gl.VERTEX_SHADER, `
  attribute vec2 p; varying vec2 uv;
  void main(){ uv=p*.5+.5; gl_Position=vec4(p,0.,1.); }
`));
gl.attachShader(feedbackProgram, compileShader(gl.FRAGMENT_SHADER, `
  precision mediump float; varying vec2 uv;
  uniform sampler2D previousEnergy; uniform sampler2D currentLight;
  uniform float retention; uniform float charge;
  void main(){
    vec3 oldEnergy=texture2D(previousEnergy,uv).rgb;
    vec3 exposure=texture2D(currentLight,uv).rgb;
    // Charge towards the actual emitted intensity, never towards white.
    // When the beam becomes darker, retain and decay the previous energy.
    vec3 rising=mix(oldEnergy,exposure,charge);
    vec3 decaying=oldEnergy*retention;
    vec3 nextEnergy=mix(decaying,rising,step(oldEnergy,exposure));
    gl_FragColor=vec4(nextEnergy,1.0);
  }
`));
gl.linkProgram(feedbackProgram);
const feedbackPosition = gl.getAttribLocation(feedbackProgram, 'p');
const energyTextures = [gl.createTexture(), gl.createTexture()];
const energyFramebuffers = [gl.createFramebuffer(), gl.createFramebuffer()];
let energyIndex = 0;

function configureTexture(texture) {
  gl.bindTexture(gl.TEXTURE_2D, texture);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
}

function allocateEnergyTextures() {
  for (let i=0; i<2; i++) {
    configureTexture(energyTextures[i]);
    gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,canvas.width,canvas.height,0,gl.RGBA,gl.UNSIGNED_BYTE,null);
    gl.bindFramebuffer(gl.FRAMEBUFFER,energyFramebuffers[i]);
    gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,energyTextures[i],0);
    gl.viewport(0,0,canvas.width,canvas.height);
    gl.clearColor(0,0,0,1); gl.clear(gl.COLOR_BUFFER_BIT);
  }
  gl.bindFramebuffer(gl.FRAMEBUFFER,null);
  energyIndex=0;
}

const geometry = Object.assign({ hSize: 91, vSize: 87, xPos: 0, yPos: 0, curve: 10, brightness: 1.25, contrast: 1.25, focus: 0.92, glow: 1.15, flicker: 0.48 },
  JSON.parse(localStorage.getItem('crtGeometry') || '{}'));

function applyGeometry() {
  const leftPct = (100 - geometry.hSize) / 2 + geometry.xPos;
  const topPct = (100 - geometry.vSize) / 2 + geometry.yPos;
  screen.style.left = `${leftPct}%`;
  screen.style.top = `${topPct}%`;
  screen.style.width = `${geometry.hSize}%`;
  screen.style.height = `${geometry.vSize}%`;
  screen.style.borderRadius = `${geometry.curve}% / ${geometry.curve * 0.72}%`;
  localStorage.setItem('crtGeometry', JSON.stringify(geometry));
  document.querySelectorAll('.knob').forEach(knob => {
    const min = +knob.dataset.min, max = +knob.dataset.max;
    const t = (geometry[knob.dataset.key] - min) / (max - min);
    knob.style.setProperty('--angle', `${-135 + t * 270}deg`);
    knob.title = `${knob.dataset.key}: ${geometry[knob.dataset.key].toFixed(1)}`;
  });
  resize();
}

function resize() {
  const dpr = Math.min(2, Math.max(1.75, devicePixelRatio || 1));
  const width = screen.clientWidth;
  const height = screen.clientHeight;
  canvas.width = current.width = Math.floor(width * dpr);
  canvas.height = current.height = Math.floor(height * dpr);
  canvas.style.width = width + 'px';
  canvas.style.height = height + 'px';

  // A rectangular PTY must fit inside the narrowest part of the barrel-
  // distorted glass. TUIs otherwise use columns that disappear at corners.
  textLeft = Math.round(width * 0.075);
  textTop = Math.round(height * 0.045);
  const usableW = width * 0.85;
  const usableH = height * 0.90;
  fontSize = Math.max(12, Math.min(22, usableH / 38 * 0.76));
  cellH = fontSize * 1.28;

  cctx.font = `${fontSize * dpr}px ${fontFamily}`;
  cellW = cctx.measureText('M').width / dpr;
  cols = Math.max(20, Math.floor(usableW / cellW));
  // AsciiTeX output is 108 cells wide. Keep a safety margin so a full line
  // never reaches xterm's delayed-wrap column.
  if (cols < 120) {
    fontSize = Math.max(9, fontSize * (cols / 120) * 0.97);
    cellH = fontSize * 1.28;
    cctx.font = `${fontSize * dpr}px ${fontFamily}`;
    cellW = cctx.measureText('M').width / dpr;
    cols = Math.max(20, Math.floor(usableW / cellW));
  }
  rows = Math.max(8, Math.floor(usableH / cellH));
  term.resize(cols, rows);
  window.retroTerminal.resize(cols, rows);
  allocateEnergyTextures();
  updateStatus();
}

function renderCurrent(dpr) {
  cctx.clearRect(0, 0, current.width, current.height);
  cctx.save();
  cctx.scale(dpr, dpr);
  cctx.font = `${fontSize}px ${fontFamily}`;
  cctx.fontKerning = 'none';
  cctx.textBaseline = 'top';
  cctx.shadowBlur = 0;

  const buffer = term.buffer.active;
  // Paint backgrounds first, including cells containing spaces. ANSI 16/256/
  // RGB backgrounds therefore remain real rectangular terminal cells.
  for (let y = 0; y < rows; y++) {
    const line = buffer.getLine(buffer.viewportY + y);
    if (!line) continue;
    for (let x = 0; x < cols; x++) {
      const cell = line.getCell(x);
      if (!cell) continue;
      const paint = cellPaint(cell);
      if (paint.bg) {
        cctx.globalAlpha = 1;
        cctx.fillStyle = paint.bg;
        cctx.fillRect(textLeft + x * cellW, textTop + y * cellH, cellW + 0.35, cellH + 0.35);
      }
    }
  }
  for (let y = 0; y < rows; y++) {
    const line = buffer.getLine(buffer.viewportY + y);
    if (!line) continue;
    // xterm's buffer owns the grid. Draw every glyph at its absolute cell
    // coordinate without cumulative text-run advances. Narrow fallback glyphs
    // are centered, while only over-wide glyphs are compressed into their
    // xterm-owned cell span; nothing is stretched to fake monospace.
    for (let x = 0; x < cols; x++) {
      const cell = line.getCell(x);
      if (!cell) continue;
      const chars = cell.getChars();
      if (!chars) continue;
      if (cell.isBlink() && !blinkVisible) continue;
      const cellSpan = Math.max(1, cell.getWidth());
      const paint = cellPaint(cell);
      cctx.globalAlpha = cell.isDim() ? 0.42 : 0.72;
      cctx.fillStyle = paint.fg;
      cctx.shadowColor = paint.fg;
      const targetW = cellW * cellSpan;
      const measured = cctx.measureText(chars).width;
      const originX = textLeft + x * cellW;
      cctx.save();
      cctx.translate(originX, textTop + y * cellH);
      if (measured > targetW * 1.015) cctx.scale(targetW / measured, 1);
      cctx.textAlign = 'left';
      cctx.fillText(chars, 0, 0);
      cctx.restore();
      if (cell.isUnderline()) {
        cctx.globalAlpha = 0.72;
        cctx.fillStyle = paint.fg;
        cctx.fillRect(textLeft + x * cellW, textTop + (y + 0.89) * cellH, targetW, Math.max(1, fontSize / 14));
      }
      if (cell.isOverline()) {
        cctx.globalAlpha = 0.72;
        cctx.fillStyle = paint.fg;
        cctx.fillRect(textLeft + x * cellW, textTop + y * cellH + Math.max(0.5, fontSize * 0.03), targetW, Math.max(1, fontSize / 14));
      }
      x += cellSpan - 1;
    }
  }

  if (cursorVisible) {
    cctx.globalAlpha = 1;
    cctx.fillStyle = 'rgba(150,255,185,0.78)';
    cctx.fillRect(textLeft + buffer.cursorX * cellW, textTop + buffer.cursorY * cellH + cellH * .82, cellW, 2.5);
  }
  if (mouseTestOverlay) {
    cctx.globalAlpha = 0.96;
    cctx.fillStyle = 'rgba(0,12,5,0.94)';
    cctx.fillRect(textLeft, textTop + 4 * cellH, Math.min(760, cols * cellW), cellH * 1.15);
    cctx.fillStyle = 'rgb(72,255,132)';
    cctx.font = `${fontSize}px ${fontFamily}`;
    cctx.textAlign = 'left';
    cctx.fillText(mouseTestMessage, textLeft, textTop + 4 * cellH);
  }
  if (mouseCalibration) {
    cctx.globalAlpha = 0.95;
    cctx.font = `${fontSize}px ${fontFamily}`;
    cctx.textAlign = 'left';
    for (const target of calibrationTargets()) {
      const x = textLeft + target.col * cellW;
      const y = textTop + target.row * cellH;
      cctx.fillStyle = 'rgba(4,55,22,0.92)';
      cctx.fillRect(x, y, 13 * cellW, 3 * cellH);
      cctx.strokeStyle = 'rgb(72,255,132)';
      cctx.lineWidth = 1.5;
      cctx.strokeRect(x, y, 13 * cellW, 3 * cellH);
      cctx.fillStyle = 'rgb(72,255,132)';
      cctx.fillText(target.name, x + cellW, y + cellH * 0.72);
    }
    cctx.fillStyle = 'rgba(0,10,4,0.96)';
    cctx.fillRect(textLeft, textTop, Math.min(cols * cellW, 900), cellH * 2.2);
    cctx.fillStyle = 'rgb(92,255,148)';
    cctx.fillText(calibrationMessage, textLeft + cellW, textTop + cellH * 0.45);
  }
  cctx.restore();
}

function animate(now) {
  const dpr = Math.min(2, Math.max(1.75, devicePixelRatio || 1));
  const dt = Math.min(0.1, (now - last) / 1000);
  last = now;
  cursorVisible = Math.floor(now / 520) % 2 === 0;
  blinkVisible = Math.floor(now / 500) % 2 === 0;
  const activeBuffer = term.buffer.active;
  const alternateBuffer = activeBuffer === term.buffer.alternate;
  const bufferSwitched = alternateBuffer !== lastAlternateBuffer;
  if (bufferSwitched) {
    lastAlternateBuffer = alternateBuffer;
    // Never blend a full-screen TUI with the shell that replaces it. They are
    // distinct CRT pages, not two exposures of the same character cells.
    allocateEnergyTextures();
    lastScrollAt = now;
  }
  const bufferAdvanced = activeBuffer.baseY !== lastBaseY;
  if (bufferAdvanced) {
    lastBaseY = activeBuffer.baseY;
    lastScrollAt = now;
  }
  renderCurrent(dpr);

  // Persistence is spatially neutral: vertical scrolling must retain the
  // same per-pixel phosphor energy as horizontal edits. Only a true buffer
  // page switch clears exposure; active redraw merely decays somewhat faster.
  const activelyRedrawing = now - lastTerminalDataAt < 180;
  const halfLife = now - lastScrollAt < 320 ? 0.22 : activelyRedrawing ? 0.28 : 0.65;
  const retention = bufferSwitched ? 0.0 : Math.pow(0.5, dt / halfLife);
  const charge = 1.0 - Math.exp(-dt / 0.14);
  gl.bindTexture(gl.TEXTURE_2D, glTexture);
  gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, current);

  const nextEnergy = 1 - energyIndex;
  gl.bindFramebuffer(gl.FRAMEBUFFER, energyFramebuffers[nextEnergy]);
  gl.viewport(0, 0, canvas.width, canvas.height);
  gl.useProgram(feedbackProgram);
  gl.bindBuffer(gl.ARRAY_BUFFER, glBuffer);
  gl.enableVertexAttribArray(feedbackPosition);
  gl.vertexAttribPointer(feedbackPosition,2,gl.FLOAT,false,0,0);
  gl.activeTexture(gl.TEXTURE0); gl.bindTexture(gl.TEXTURE_2D, energyTextures[energyIndex]);
  gl.uniform1i(gl.getUniformLocation(feedbackProgram,'previousEnergy'),0);
  gl.activeTexture(gl.TEXTURE1); gl.bindTexture(gl.TEXTURE_2D, glTexture);
  gl.uniform1i(gl.getUniformLocation(feedbackProgram,'currentLight'),1);
  gl.uniform1f(gl.getUniformLocation(feedbackProgram,'retention'),retention);
  gl.uniform1f(gl.getUniformLocation(feedbackProgram,'charge'),charge);
  gl.drawArrays(gl.TRIANGLES,0,3);
  energyIndex=nextEnergy;

  gl.bindFramebuffer(gl.FRAMEBUFFER, null);
  gl.viewport(0, 0, canvas.width, canvas.height);
  gl.useProgram(glProgram);
  gl.bindBuffer(gl.ARRAY_BUFFER, glBuffer);
  gl.enableVertexAttribArray(glPosition);
  gl.vertexAttribPointer(glPosition,2,gl.FLOAT,false,0,0);
  gl.activeTexture(gl.TEXTURE0);
  gl.bindTexture(gl.TEXTURE_2D, energyTextures[energyIndex]);
  gl.uniform1i(gl.getUniformLocation(glProgram,'phosphor'),0);
  gl.activeTexture(gl.TEXTURE1);
  gl.bindTexture(gl.TEXTURE_2D, glTexture);
  gl.uniform1i(gl.getUniformLocation(glProgram,'liveText'),1);
  gl.uniform1f(gl.getUniformLocation(glProgram, 'barrel'), 0.015 + geometry.curve * 0.0045);
  gl.uniform1f(gl.getUniformLocation(glProgram, 'brightness'), geometry.brightness);
  gl.uniform1f(gl.getUniformLocation(glProgram, 'contrast'), geometry.contrast);
  gl.uniform1f(gl.getUniformLocation(glProgram, 'focus'), geometry.focus);
  gl.uniform1f(gl.getUniformLocation(glProgram, 'glow'), geometry.glow);
  gl.uniform1f(gl.getUniformLocation(glProgram, 'flicker'), geometry.flicker);
  gl.uniform1f(gl.getUniformLocation(glProgram, 'time'), now / 1000);
  gl.uniform2f(gl.getUniformLocation(glProgram, 'resolution'), canvas.width, canvas.height);
  gl.drawArrays(gl.TRIANGLES, 0, 3);
  requestAnimationFrame(animate);
}

const mouseMode = { tracking: 'none', sgr: false, win32Input: false, tail: '' };

function hexText(text) {
  return [...new TextEncoder().encode(text)].map(value => value.toString(16).padStart(2, '0')).join('');
}

function reportTerminalCapabilities(probe, oldTailLength) {
  const isNew = match => match.index + match[0].length > oldTailLength;
  let match;

  const decrqm = /\x1b\[\?(\d+)\$p/g;
  while ((match = decrqm.exec(probe))) if (isNew(match)) {
    const mode = +match[1];
    const protocol = term._core?.coreMouseService?.activeProtocol;
    const encoding = term._core?.coreMouseService?.activeEncoding;
    let status = 0;
    const known = set => { status = set ? 1 : 2; };
    if (mode === 1000) known(protocol === 'VT200');
    else if (mode === 1002) known(protocol === 'DRAG');
    else if (mode === 1003) known(protocol === 'ANY' || forcedMouseCapture);
    else if (mode === 1006) known(encoding === 'SGR' || forcedMouseCapture);
    else if (mode === 1049) known(term.buffer.active === term.buffer.alternate);
    else if (mode === 2004) known(term.modes.bracketedPasteMode);
    else if (mode === 1) known(term.modes.applicationCursorKeysMode);
    else if (mode === 6) known(term.modes.originMode);
    else if (mode === 7) known(term.modes.wraparoundMode);
    else if (mode === 25) known(true);
    window.retroTerminal.input(`\x1b[?${mode};${status}$y`);
  }

  const xtversion = /\x1b\[>\d*q/g;
  while ((match = xtversion.exec(probe))) if (isNew(match))
    window.retroTerminal.input('\x1bP>|RasterGlow-Terminal 1.0.0\x1b\\');

  const xtget = /\x1bP\+q([0-9a-fA-F;]+)\x1b\\/g;
  while ((match = xtget.exec(probe))) if (isNew(match)) {
    const values = {
      TN: 'xterm-256color', Co: '256', RGB: '8/8/8',
      Tc: true
    };
    for (const encodedName of match[1].split(';')) {
      const name = new TextDecoder().decode(Uint8Array.from(encodedName.match(/../g) || [], byte => parseInt(byte, 16)));
      if (!(name in values)) window.retroTerminal.input(`\x1bP0+r${encodedName}\x1b\\`);
      else {
        const value = values[name];
        window.retroTerminal.input(`\x1bP1+r${encodedName}${value === true ? '' : '=' + hexText(value)}\x1b\\`);
      }
    }
  }

  const oscColor = /\x1b\](10|11);\?(?:\x07|\x1b\\)/g;
  while ((match = oscColor.exec(probe))) if (isNew(match)) {
    const rgb = match[1] === '10' ? '2aff/ffff/66ff' : '0000/0500/0300';
    window.retroTerminal.input(`\x1b]${match[1]};rgb:${rgb}\x1b\\`);
  }

  const winQuery = /\x1b\[(14|16)t/g;
  while ((match = winQuery.exec(probe))) if (isNew(match)) {
    if (match[1] === '14') window.retroTerminal.input(`\x1b[4;${screen.clientHeight};${screen.clientWidth}t`);
    else window.retroTerminal.input(`\x1b[6;${Math.round(cellH)};${Math.round(cellW)}t`);
  }
}

function observeTerminalModes(data) {
  const oldTailLength = mouseMode.tail.length;
  const probe = mouseMode.tail + data;
  reportTerminalCapabilities(probe, oldTailLength);
  if (probe.includes('\x1b]777;mouse=on\x07')) {
    forcedMouseCapture = true;
    mouseTestOverlay = true;
    mouseDiagnostic = 'MAUS SGR AKTIV';
    updateStatus();
  }
  if (probe.includes('\x1b]777;mouse=off\x07')) {
    forcedMouseCapture = false;
    mouseTestOverlay = false;
    mouseDiagnostic = '';
    updateStatus();
  }
  if (probe.includes('\x1b]777;mouse=calibrate\x07')) {
    forcedMouseCapture = true;
    mouseTestOverlay = false;
    mouseCalibration = true;
    mouseDiagnostic = 'MAUS-KALIBRIERUNG';
    updateStatus();
  }
  if (probe.includes('\x1b]777;mouse=calibrate-off\x07')) {
    forcedMouseCapture = false;
    mouseCalibration = false;
    mouseDiagnostic = '';
    updateStatus();
  }
  const re = /\x1b\[\?([0-9;]+)([hl])/g;
  let match;
  while ((match = re.exec(probe))) {
    const enabled = match[2] === 'h';
    for (const mode of match[1].split(';')) {
      if (mode === '9001') mouseMode.win32Input = enabled;
      else if (mode === '1006') mouseMode.sgr = enabled;
      else if (['1000','1002','1003'].includes(mode) && enabled) mouseMode.tracking = mode;
      else if (mouseMode.tracking === mode) mouseMode.tracking = 'none';
    }
    if (match[1].split(';').some(mode => ['1000','1002','1003','1006'].includes(mode)))
      mouseDiagnostic = enabled ? `MAUS ${match[1]} AKTIV` : '';
    updateStatus();
  }
  mouseMode.tail = probe.slice(-64);
}

window.retroTerminal.onData(data => {
  lastTerminalDataAt = performance.now();
  observeTerminalModes(data);
  // xterm-headless currently ignores SGR 6 (rapid blink). Preserve terminal
  // semantics by degrading it to supported SGR 5 instead of printing or
  // silently losing the attribute.
  const normalized = data.replace(/\x1b\[([0-9;]*)m/g, (sequence, parameters) => {
    const values = parameters.split(';');
    return values.includes('6') ? `\x1b[${values.map(value => value === '6' ? '5' : value).join(';')}m` : sequence;
  });
  term.write(normalized);
});
window.retroTerminal.onExit(() => term.write('\r\n\x1b[31m[PowerShell beendet]\x1b[0m'));

function terminalMouseCell(event) {
  const rect = screen.getBoundingClientRect();
  const uvx = (event.clientX - rect.left) / rect.width;
  const uvy = 1 - (event.clientY - rect.top) / rect.height;
  const qx = uvx * 2 - 1, qy = uvy * 2 - 1;
  const barrel = 0.015 + geometry.curve * 0.0045;
  const factor = 1 + barrel * (qx * qx + qy * qy);
  const sourceX = (qx * factor + 1) * 0.5 * screen.clientWidth;
  const sourceY = (1 - (qy * factor + 1) * 0.5) * screen.clientHeight;
  return {
    col: Math.max(0, Math.min(cols - 1, Math.floor((sourceX - textLeft) / cellW))),
    row: Math.max(0, Math.min(rows - 1, Math.floor((sourceY - textTop) / cellH))),
    x: Math.max(1, Math.round(sourceX)),
    y: Math.max(1, Math.round(sourceY))
  };
}

let pressedMouseButton = -1;
function sendMouse(event, button, action) {
  const cell = terminalMouseCell(event);
  const tracking = forcedMouseCapture ? '1003' : mouseMode.tracking;
  const isMove = action === 32;
  if (tracking === 'none' || (isMove && tracking === '1000') || (isMove && tracking === '1002' && pressedMouseButton < 0)) return false;
  const packet = sgrMouseSequence({
    button, action, col: cell.col, row: cell.row,
    shiftKey: event.shiftKey, altKey: event.altKey, ctrlKey: event.ctrlKey
  });
  window.retroTerminal.input(packet);
  const sent = true;
  if (sent) {
    const names = action === 32 ? 'MOVE' : button === 4 ? (action === 0 ? 'RAD↑' : 'RAD↓') : action === 0 ? 'UP' : 'DOWN';
    mouseDiagnostic = `MAUS ${names} C${cell.col + 1} R${cell.row + 1}`;
    mouseTestMessage = `Event: ${names}   column=${cell.col + 1}   row=${cell.row + 1}   SGR forwarded to ConPTY`;
    updateStatus();
  }
  return sent;
}

screen.addEventListener('pointerdown', event => {
  const button = event.button === 0 ? 0 : event.button === 1 ? 1 : event.button === 2 ? 2 : -1;
  if (button === 0 && mouseCalibration) {
    const cell = terminalMouseCell(event);
    const targets = calibrationTargets();
    const nearest = targets.reduce((best, target) => {
      const centerCol = target.col + 6, centerRow = target.row + 1;
      const distance = Math.hypot(cell.col - centerCol, cell.row - centerRow);
      return !best || distance < best.distance ? { target, centerCol, centerRow, distance } : best;
    }, null);
    calibrationMessage = `${nearest.target.name}: clicked C${cell.col + 1}/R${cell.row + 1}, target center C${nearest.centerCol + 1}/R${nearest.centerRow + 1}, error ΔC=${cell.col - nearest.centerCol}, ΔR=${cell.row - nearest.centerRow}`;
  }
  if (button >= 0 && sendMouse(event, button, 1)) {
    pressedMouseButton = button;
    screen.setPointerCapture(event.pointerId);
    event.preventDefault();
  }
});
screen.addEventListener('pointerup', event => {
  if (pressedMouseButton >= 0 && sendMouse(event, pressedMouseButton, 0)) event.preventDefault();
  pressedMouseButton = -1;
});
screen.addEventListener('pointermove', event => {
  if (sendMouse(event, pressedMouseButton >= 0 ? pressedMouseButton : 3, 32)) event.preventDefault();
});
screen.addEventListener('wheel', event => {
  if (sendMouse(event, 4, event.deltaY < 0 ? 0 : 1)) event.preventDefault();
}, { passive: false });
screen.addEventListener('contextmenu', event => {
  if (mouseMode.tracking !== 'none' || forcedMouseCapture) event.preventDefault();
});

const pressedKeys = new Set();
const interceptedKeyUps = new Set();
function resetKeyboardState() {
  pressedKeys.clear();
  interceptedKeyUps.clear();
}

function reconcileModifierState(event) {
  // Browsers do not dispatch keyup when focus is lost while a modifier is
  // held. Remove those stale keys before encoding the next Win32 record.
  if (!event.shiftKey) { pressedKeys.delete('ShiftLeft'); pressedKeys.delete('ShiftRight'); }
  if (!event.ctrlKey) { pressedKeys.delete('ControlLeft'); pressedKeys.delete('ControlRight'); }
  if (!event.altKey) { pressedKeys.delete('AltLeft'); pressedKeys.delete('AltRight'); }
  if (!event.metaKey) { pressedKeys.delete('MetaLeft'); pressedKeys.delete('MetaRight'); }
}

window.addEventListener('keydown', event => {
  reconcileModifierState(event);
  if (event.ctrlKey && event.shiftKey && event.key === 'F2') {
    interceptedKeyUps.add(event.code);
    document.getElementById('controls').classList.toggle('hidden');
    event.preventDefault(); return;
  }
  if (event.ctrlKey && event.shiftKey && event.key === 'F3') {
    interceptedKeyUps.add(event.code);
    forcedMouseCapture = !forcedMouseCapture;
    mouseDiagnostic = forcedMouseCapture ? 'MAUS SGR MANUELL' : '';
    updateStatus();
    event.preventDefault(); return;
  }
  if (event.ctrlKey && event.shiftKey && event.key === 'F11') {
    interceptedKeyUps.add(event.code);
    ipcRenderer.send('window:fullscreen');
    event.preventDefault(); return;
  }
  if (event.ctrlKey && event.shiftKey && event.key.toLowerCase() === 'v') {
    interceptedKeyUps.add(event.code);
    term.scrollToBottom();
    navigator.clipboard.readText().then(text => window.retroTerminal.input(text));
    event.preventDefault(); return;
  }
  if (mouseMode.win32Input) {
    pressedKeys.add(event.code);
    const locks = { num: event.getModifierState('NumLock'), scroll: event.getModifierState('ScrollLock'), caps: event.getModifierState('CapsLock'), pressed: pressedKeys };
    term.scrollToBottom();
    window.retroTerminal.input(win32KeySequence(event, true, locks));
    event.preventDefault(); return;
  }
  if (event.ctrlKey && event.key.toLowerCase() === 'c') {
    term.scrollToBottom();
    window.retroTerminal.input('\x03'); event.preventDefault(); return;
  }
  if (event.ctrlKey && !event.altKey && !event.metaKey) {
    const key = event.key.toLowerCase();
    let control = null;
    if (key.length === 1 && key >= 'a' && key <= 'z') control = String.fromCharCode(key.charCodeAt(0) - 96);
    else if (key === ' ' || key === '@') control = '\x00';
    else if (key === '[') control = '\x1b';
    else if (key === '\\') control = '\x1c';
    else if (key === ']') control = '\x1d';
    else if (key === '^') control = '\x1e';
    else if (key === '_') control = '\x1f';
    else if (key === '?') control = '\x7f';
    if (control !== null) {
      term.scrollToBottom();
      window.retroTerminal.input(control);
      event.preventDefault(); return;
    }
  }
  const special = {
    Enter: '\r', Backspace: '\x7f', Tab: '\t', Escape: '\x1b',
    ArrowUp: '\x1b[A', ArrowDown: '\x1b[B', ArrowRight: '\x1b[C', ArrowLeft: '\x1b[D',
    Home: '\x1b[H', End: '\x1b[F', Delete: '\x1b[3~', PageUp: '\x1b[5~', PageDown: '\x1b[6~'
  };
  if (special[event.key]) { term.scrollToBottom(); window.retroTerminal.input(special[event.key]); event.preventDefault(); }
  else if (event.key.length === 1 && !event.ctrlKey && !event.metaKey) {
    term.scrollToBottom();
    window.retroTerminal.input(event.key); event.preventDefault();
  }
}, true);

window.addEventListener('keyup', event => {
  if (interceptedKeyUps.delete(event.code)) { event.preventDefault(); return; }
  if (!mouseMode.win32Input) return;
  pressedKeys.delete(event.code);
  const locks = { num: event.getModifierState('NumLock'), scroll: event.getModifierState('ScrollLock'), caps: event.getModifierState('CapsLock'), pressed: pressedKeys };
  window.retroTerminal.input(win32KeySequence(event, false, locks));
  event.preventDefault();
}, true);

window.addEventListener('blur', resetKeyboardState);
window.addEventListener('focus', resetKeyboardState);
document.addEventListener('visibilitychange', () => {
  if (document.hidden) resetKeyboardState();
});
ipcRenderer.on('terminal:resume', () => {
  resetKeyboardState();
  term.scrollToBottom();
});

window.addEventListener('resize', resize);
document.querySelectorAll('.knob').forEach(knob => {
  knob.addEventListener('pointerdown', event => {
    knob.setPointerCapture(event.pointerId);
    const key = knob.dataset.key;
    const min = +knob.dataset.min, max = +knob.dataset.max;
    const startY = event.clientY, startValue = geometry[key];
    const move = e => {
      geometry[key] = Math.max(min, Math.min(max, startValue + (startY - e.clientY) * (max - min) / 140));
      applyGeometry();
    };
    knob.addEventListener('pointermove', move);
    knob.addEventListener('pointerup', () => knob.removeEventListener('pointermove', move), { once: true });
  });
  knob.addEventListener('wheel', event => {
    const key = knob.dataset.key, min = +knob.dataset.min, max = +knob.dataset.max;
    geometry[key] = Math.max(min, Math.min(max, geometry[key] - Math.sign(event.deltaY) * (max - min) / 50));
    applyGeometry(); event.preventDefault();
  }, { passive: false });
});
document.fonts.load('16px "AsciiTeX Unicode Mono"').then(() => document.fonts.ready).then(() => {
  applyGeometry();
  requestAnimationFrame(animate);
});
